### ISSUE TITLE
When multiple processes are started, duplicate ports will be bound

### ISSUE THREAD

**Issue by realLiangshiwei** [Mongo2Go/Mongo2Go#115]
The rider can set the number of assemblies in parallel, when multiple processes get available ports, mong2go get duplicate ports and throw an exception

![image](https://user-images.githubusercontent.com/16813853/113964584-5a0bc280-985e-11eb-9f45-09893f699fd2.png)

```
MongoDB.Driver.MongoCommandException
Command replSetInitiate failed: already initialized.
   at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.ProcessResponse(ConnectionId connectionId, CommandMessage responseMessage)
   at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.WireProtocol.CommandWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.ServerChannel.ExecuteProtocol[TResult](IWireProtocol`1 protocol, ICoreSession session, CancellationToken cancellationToken)
```

So, in multi-process, we cannot be sure that the port is available.

https://github.com/Mongo2Go/Mongo2Go/blob/efa02f5ec7b99fcfee1616bac8d38f35f66c13e1/src/Mongo2Go/Helper/PortWatcher.cs#L31

> Use a port number of zero if you want the underlying service provider to assign a free port for you

https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket?view=net-5.0#remarks

**Comment by JohannesHoppe** [comment]
As always, I will publish any PR that has green tests! 😉
