### ISSUE TITLE
Arm64 support 

### ISSUE THREAD

**Issue by Jishun** [Mongo2Go/Mongo2Go#127]
Any chance to add arm processor support? 

I was able to use mongo2go in x64 windows and linux without having to change any code,  
it would be awesome if it can restore the proper mongo binary to the arm based linux 

at the moment it fails with message 

```
 Error Message:
   System.ComponentModel.Win32Exception : Exec format error
  Stack Trace:
     at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Mongo2Go.Helper.ProcessControl.StartAndWaitForReady(Process process, Int32 timeoutInSeconds, String processReadyIdentifier, ILogger logger)
   at Mongo2Go.Helper.MongoDbProcessStarter.Start(String binariesDirectory, String dataDirectory, Int32 port, Boolean doNotKill, Boolean singleNodeReplSet, String additionalMongodArguments, UInt16 singleNodeReplSetWaitTimeout, ILogger logger)
   at Mongo2Go.Helper.MongoDbProcessStarter.Start(String binariesDirectory, String dataDirectory, Int32 port, Boolean singleNodeReplSet, String additionalMongodArguments, UInt16 singleNodeReplSetWaitTimeout, ILogger logger)
   at Mongo2Go.MongoDbRunner..ctor(IPortPool portPool, IFileSystem fileSystem, IMongoDbProcessStarter processStarter, IMongoBinaryLocator mongoBin, String dataDirectory, Boolean singleNodeReplSet, String additionalMongodArguments, UInt16 singleNodeReplSetWaitTimeout, ILogger logger)
   at Mongo2Go.MongoDbRunner.Start(String dataDirectory, String binariesSearchPatternOverride, String binariesSearchDirectory, Boolean singleNodeReplSet, String additionalMongodArguments, UInt16 singleNodeReplSetWaitTimeout, ILogger logger)
```

**Comment by JohannesHoppe** [comment]
Sure, why not? Just out of interest, what do you need it for? Do you really have a Linux ARM machine to develop on? Or do you run a little Mongo2Go on a Raspberry Pi?? 😄 

I'm happy to merge any PR that adds support for this. Of course, the normal linux binaries should still work – so you would need to figure out a good detection method.

**Comment by Jishun** [comment]
Thanks for your response, keen to see it working,  it's not any special reason,  just ARM is becoming as common as x86,  cloud providers now provide arm instances, people are moving to arm infra structure because it's cheaper and even more efficient for many uses such as web services. 
for local development / personal use, for instance, btw the Mac M1 is the best example to demand ARM support  too :)

**Comment by JohannesHoppe** [comment]
@balloman Do you have any progress here?

**Comment by 0xced** [comment]
That was #130 but it got closed because I improved the downloader tool to support platform/architecture combinations in a more future proof way for macOS and Windows.

But now I'm having concerns about the size of the NuGet package. I will open a new issue with a proposal.

**Comment by JohannesHoppe** [comment]
# 👍

**Comment by 0xced** [comment]
I just opened #133 with the proposal.

**Comment by JohannesHoppe** [comment]
Hi @Jishun — good news: **Mongo2Go 4.2.0** now bundles native **Linux arm64** binaries for `mongod`, `mongoimport` and `mongoexport`, and binary resolution is architecture-aware, so the right build is selected automatically on your platform.

One caveat: this covers **Linux arm64**. Native macOS arm64 (Apple Silicon) isn't included yet — MongoDB 4.4 has no macOS arm64 build, so on a Mac the x64 binaries still run under Rosetta 2. Native macOS arm64 will come with the MongoDB 8.x upgrade (#132).

Once 4.2.0 is on NuGet, please give it a try on your ARM setup and let us know how it goes! 🙏

**Comment by JohannesHoppe** [comment]
For anyone watching: arm64 support is now complete. Linux arm64 shipped in 4.2.0, and **Mongo2Go 5.0.0** adds a **native macOS arm64 (Apple Silicon)** build — no more running x64 binaries under Rosetta 2. Bundled platforms are now Windows x64, Linux x64 & arm64, and macOS x64 & arm64.
