### ISSUE TITLE
Mongo2Go 3.X.X Not working in GitlabCI

### ISSUE THREAD

**Issue by BLaZeKiLL** [Mongo2Go/Mongo2Go#135]
Recently updated from 2.2.9 -> 3.1.3, Working Locally But Does Not Work Gitlab

![image](https://user-images.githubusercontent.com/33104478/153334764-f986670c-ec05-4a5c-b4e6-47b6503127a8.png)

I use the single node replica set options and increased the timeout to max still no effect

**Comment by BLaZeKiLL** [comment]
Works fine on 2.2.16 Also

**Comment by maximal096** [comment]
What image are you using? Seems to run fine for me now, though I´ve also previously had problems. It seems platform specific. Also possible that .net 6 might have fixed it. Not sure.

```yml
image: mcr.microsoft.com/dotnet/sdk:6.0.101-bullseye-slim-amd64

stages:
    - test
test:
    stage: test
    before_script:
        - 'apt-get update'
        - 'apt-get upgrade -y'
        - 'chmod +x ./tests/run.sh'
    script:
        - dotnet restore
        - ./tests/run.sh
```

The bash script just finds all the tests, since ```dotnet test``` does not find any.

```bash
#!/bin/bash

find ./tests -maxdepth 1 -mindepth 1 -type d | while read d; do
    dotnet test $d/
done
```

**Comment by seanat280** [comment]
FWIW this exact same issue happens on Appveyor as well when using the "Ubuntu1804" image, and it works correctly on 2.2.16.  We just locked to that version assuming that it was a known issue.

`[00:20:09] [20:15:21 ERR] R-FAULT rabbitmq://localhost:5673/TwoEightyCap.Service.ExternalMarkets.Consumers:ExternalMarketsRequest 42260000-5da5-0015-f3a0-08d9158298de TwoEightyCap.Service.ExternalMarkets.Common.Requests.BulkQRRequest TwoEightyCap.Service.ExternalMarkets.Consumers.ExternalMarketsRequestConsumer(00:00:30.3481657)
[00:20:09] System.AggregateException: One or more errors occurred. (A timeout occurred after 30000ms selecting a server using CompositeServerSelector{ Selectors = MongoDB.Driver.MongoClient+AreSessionsSupportedServerSelector, LatencyLimitingServerSelector{ AllowedLatencyRange = 00:00:00.0150000 } }. Client view of cluster state is { ClusterId : "1", Type : "Unknown", State : "Disconnected", Servers : [{ ServerId: "{ ClusterId : 1, EndPoint : "127.0.0.1:34893" }", EndPoint: "127.0.0.1:34893", ReasonChanged: "Heartbeat", State: "Disconnected", ServerVersion: , TopologyVersion: , Type: "Unknown", HeartbeatException: "MongoDB.Driver.MongoConnectionException: An exception occurred while opening a connection to the server.
[00:20:09]  ---> System.Net.Sockets.SocketException (111): Connection refused
[00:20:09]    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
[00:20:09]    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
[00:20:09]    at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
[00:20:09] --- End of stack trace from previous location ---
[00:20:09]    at MongoDB.Driver.Core.Connections.TcpStreamFactory.ConnectAsync(Socket socket, EndPoint endPoint, CancellationToken cancellationToken)
[00:20:09]    at MongoDB.Driver.Core.Connections.TcpStreamFactory.CreateStreamAsync(EndPoint endPoint, CancellationToken cancellationToken)
[00:20:09]    at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync(CancellationToken cancellationToken)
[00:20:09]    --- End of inner exception stack trace ---
[00:20:09]    at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync(CancellationToken cancellationToken)
[00:20:09]    at MongoDB.Driver.Core.Servers.ServerMonitor.InitializeConnectionAsync(CancellationToken cancellationToken)
[00:20:09]    at MongoDB.Driver.Core.Servers.ServerMonitor.HeartbeatAsync(CancellationToken cancellationToken)", LastHeartbeatTimestamp: "2021-05-12T20:15:21.0055290Z", LastUpdateTimestamp: "2021-05-12T20:15:21.0055294Z" }] }.)
[00:20:09]  ---> System.TimeoutException: A timeout occurred after 30000ms selecting a server using CompositeServerSelector{ Selectors = MongoDB.Driver.MongoClient+AreSessionsSupportedServerSelector, LatencyLimitingServerSelector{ AllowedLatencyRange = 00:00:00.0150000 } }. Client view of cluster state is { ClusterId : "1", Type : "Unknown", State : "Disconnected", Servers : [{ ServerId: "{ ClusterId : 1, EndPoint : "127.0.0.1:34893" }", EndPoint: "127.0.0.1:34893", ReasonChanged: "Heartbeat", State: "Disconnected", ServerVersion: , TopologyVersion: , Type: "Unknown", HeartbeatException: "MongoDB.Driver.MongoConnectionException: An exception occurred while opening a connection to the server.
[00:20:09]  ---> System.Net.Sockets.SocketException (111): Connection refused
[00:20:09]    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
[00:20:09]    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
[00:20:09]    at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
[00:20:09] --- End of stack trace from previous location ---
[00:20:09]    at MongoDB.Driver.Core.Connections.TcpStreamFactory.ConnectAsync(Socket socket, EndPoint endPoint, CancellationToken cancellationToken)
[00:20:09]    at MongoDB.Driver.Core.Connections.TcpStreamFactory.CreateStreamAsync(EndPoint endPoint, CancellationToken cancellationToken)
[00:20:09]    at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync(CancellationToken cancellationToken)
[00:20:09]    --- End of inner exception stack trace ---
[00:20:09]    at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync(CancellationToken cancellationToken)
[00:20:09]    at MongoDB.Driver.Core.Servers.ServerMonitor.InitializeConnectionAsync(CancellationToken cancellationToken)
[00:20:09]    at MongoDB.Driver.Core.Servers.ServerMonitor.HeartbeatAsync(CancellationToken cancellationToken)", LastHeartbeatTimestamp: "2021-05-12T20:15:21.0055290Z", LastUpdateTimestamp: "2021-05-12T20:15:21.0055294Z" }] }.
[00:20:09]    at MongoDB.Driver.Core.Clusters.Cluster.ThrowTimeoutException(IServerSelector selector, ClusterDescription description)
[00:20:09]    at MongoDB.Driver.Core.Clusters.Cluster.WaitForDescriptionChangedHelper.HandleCompletedTask(Task completedTask)
[00:20:09]    at MongoDB.Driver.Core.Clusters.Cluster.WaitForDescriptionChangedAsync(IServerSelector selector, ClusterDescription description, Task descriptionChangedTask, TimeSpan timeout, CancellationToken cancellationToken)
[00:20:09]    at MongoDB.Driver.Core.Clusters.Cluster.SelectServerAsync(IServerSelector selector, CancellationToken cancellationToken)
[00:20:09]    at MongoDB.Driver.MongoClient.AreSessionsSupportedAfterSeverSelctionAsync(CancellationToken cancellationToken)
[00:20:09]    at MongoDB.Driver.MongoClient.AreSessionsSupportedAsync(CancellationToken cancellationToken)
[00:20:09]    at MongoDB.Driver.MongoClient.StartImplicitSessionAsync(CancellationToken cancellationToken)
[00:20:09]    at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSessionAsync[TResult](Func`2 funcAsync, CancellationToken cancellationToken)
[00:20:09]    at TwoEightyCap.Util.EventSourcing.Repo.Mongo.MongoCrudRepo.CountAsync[T](String bucketId, Expression`1 filter, CancellationToken ct)
[00:20:09]    at TwoEightyCap.Util.EventSourcing.Migration.MigrationUtil.MigrateUpAsync(String bucketId, String name, CancellationToken ct)
[00:20:09]    at TwoEightyCap.Util.EventSourcing.Migration.MigrationUtil.MigrateAsync(String bucketId, CancellationToken ct)
[00:20:09]    --- End of inner exception stack trace ---
[00:20:09]    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
[00:20:09]    at System.Threading.Tasks.Task.Wait()
[00:20:09]    at TwoEightyCap.Util.EventSourcing.Aggregator.AggregateBuilder`1.Build()
[00:20:09]    at TwoEightyCap.Service.ExternalMarkets.Service.QuoteService..ctor(EventStore eventStore, QuoteProjections quoteProjections, TrackProjections trackProjections, IMapper mapper, ILogger`1 logger) in /home/appveyor/projects/twoeightycap-service-externalmarkets/src/TwoEightyCap.Service.ExternalMarkets/Service/QuoteService.cs:line 36
[00:20:09]    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
[00:20:09]    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[00:20:09]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
[00:20:09]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
[00:20:09]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
[00:20:09]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
[00:20:09]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
[00:20:09]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
[00:20:09]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
[00:20:09]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
[00:20:09]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
[00:20:09]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
[00:20:09]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
[00:20:09]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
[00:20:09]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
[00:20:09]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
[00:20:09]    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
[00:20:09]    at MassTransit.ExtensionsDependencyInjectionIntegration.ScopeProviders.DependencyInjectionConsumerScopeProvider.MassTransit.Scoping.IConsumerScopeProvider.GetScope[TConsumer,T](ConsumeContext`1 context)
[00:20:09]    at MassTransit.Scoping.ScopeConsumerFactory`1.Send[TMessage](ConsumeContext`1 context, IPipe`1 next)
[00:20:09]    at MassTransit.Pipeline.Filters.ConsumerMessageFilter`2.GreenPipes.IFilter<MassTransit.ConsumeContext<TMessage>>.Send(ConsumeContext`1 context, IPipe`1 next)`

**Comment by BLaZeKiLL** [comment]
Did anybody find a solution to this ? we have a few integration tests that use mongo transaction for some reason they don't work on mongo2go 2.1.16 but work fine on 3.1.3 but 3.1.3 doesn't work in our GitLab CI

**Comment by BLaZeKiLL** [comment]
would #140 fix this ?

**Comment by JohannesHoppe** [comment]
I am now releasing a new version v4, please test if the bug is gone now. If so, please get back to me so that we can close this issue.

**Comment by matthewparkes** [comment]
I can confim I'm having the same issue with 4.1.0 and using self-hosted github runner.  Tests execute no problem locally.

**Comment by nilthakkar** [comment]
Downgrading to 2.2.16 works for GitHub Action.

**Comment by JohannesHoppe** [comment]
Thanks for the updates, everyone. I still don’t have a GitLab CI setup to reproduce this myself, but I’d really like to get to the bottom of it. A few things to check:  

1. **Which image are you using?**  
   Some users reported issues on older images like `Ubuntu1804`, while `bullseye-slim` versions seem more stable. If possible, try switching to a more recent image (e.g., `mcr.microsoft.com/dotnet/sdk:6.0.101-bullseye-slim-amd64`).  

2. **Try increasing timeouts even further.**  
   You mentioned maxing them out, but in some CI environments, cold starts of MongoDB inside a container can take longer than expected. It might be worth experimenting with even higher values.  

3. **Does your CI have nested process restrictions?**  
   Some GitLab runners are configured with extra security policies that prevent background processes from spawning properly. Since Mongo2Go starts its own MongoDB process, that could be an issue. If you suspect this, try running MongoDB manually in a separate step before running your tests.  

4. **Any logs from MongoDB itself?**  
   If you can capture MongoDB’s output (`stdout` or log files), that would help us understand if it's failing to start properly or if something else is happening.  

If someone has a minimal reproduction setup, that would be super helpful. Otherwise, I’m open to merging a PR if someone can confirm a reliable fix!

**Comment by nilthakkar** [comment]
In my case, I was getting this issue because GitHub Action was using the base image ubuntu-latest.

After trying the suggestion [here](https://github.com/Mongo2Go/Mongo2Go/issues/149#issuecomment-2703136288), I did not get a timeout error, and all the integration tests passed.

**Comment by matthewparkes** [comment]
Yes this worked for me as well.  Thank you

**Comment by gabscogna** [comment]
This worked too for Azure Pipelines.

```yaml
- bash: |
    echo "deb http://security.ubuntu.com/ubuntu focal-security main" | sudo tee /etc/apt/sources.list.d/focal-security.list 
    sudo apt update 
    sudo apt install -y libssl1.1
  displayName: 'install libssl1.1 (required by MongoDB binaries)'
  continueOnError: true
```

**Comment by luizpalte** [comment]
Any possibility to work with libssl3?? I'm not able to downgrade my ubuntu version.

**Comment by JohannesHoppe** [comment]
**Mongo2Go 5.0.0** may resolve this. The usual cause of "works locally, fails on CI" with the older builds was MongoDB 4.4.4's dependency on OpenSSL 1.1 (`libcrypto.so.1.1`), which many CI images don't ship (see #149). 5.0.0 upgrades to MongoDB 8.0.26 linked against OpenSSL 3, removing that dependency. If your GitLab runner uses a modern image (glibc 2.35+), please try 5.0.0 and let us know whether the single-node replica set now starts. If your original error was something else, please reopen with the runner log and we'll dig in.
