### ISSUE TITLE
Wrong home folder is used on Linux

### ISSUE THREAD

**Issue by lemaitre-aneo** [Mongo2Go/Mongo2Go#141]
I have C# project where I use mongo2go for mocking the DB, and when I start the tests, I get the following exception:

```
  Error Message:
   System.UnauthorizedAccessException : Access to the path '/home/test' is denied.
  ----> System.IO.IOException : Permission denied
  Stack Trace:
     at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Mongo2Go.Helper.FolderSearch.FindFolder(String startPath, String searchPattern) in /_/src/Mongo2Go/Helper/FolderSearch.cs:line 35
   at Mongo2Go.Helper.FolderSearch.FindFolderUpwards(String startPath, String searchPattern) in /_/src/Mongo2Go/Helper/FolderSearch.cs:line 62
   at Mongo2Go.Helper.FolderSearch.FindFolderUpwards(String startPath, String searchPattern) in /_/src/Mongo2Go/Helper/FolderSearch.cs:line 63
   at Mongo2Go.Helper.FolderSearch.FindFolderUpwards(String startPath, String searchPattern) in /_/src/Mongo2Go/Helper/FolderSearch.cs:line 63
   at Mongo2Go.Helper.FolderSearch.FindFolderUpwards(String startPath, String searchPattern) in /_/src/Mongo2Go/Helper/FolderSearch.cs:line 63
   at Mongo2Go.Helper.FolderSearch.FindFolderUpwards(String startPath, String searchPattern) in /_/src/Mongo2Go/Helper/FolderSearch.cs:line 63
   at Mongo2Go.Helper.FolderSearch.FindFolderUpwards(String startPath, String searchPattern) in /_/src/Mongo2Go/Helper/FolderSearch.cs:line 63
   at Mongo2Go.Helper.FolderSearch.FindFolderUpwards(String startPath, String searchPattern) in /_/src/Mongo2Go/Helper/FolderSearch.cs:line 63
   at Mongo2Go.Helper.FolderSearch.FindFolderUpwards(String startPath, String searchPattern) in /_/src/Mongo2Go/Helper/FolderSearch.cs:line 63
   at Mongo2Go.Helper.MongoBinaryLocator.FindBinariesDirectory(IList`1 searchDirectories) in /_/src/Mongo2Go/Helper/MongoBinaryLocator.cs:line 84
   at Mongo2Go.Helper.MongoBinaryLocator.ResolveBinariesDirectory() in /_/src/Mongo2Go/Helper/MongoBinaryLocator.cs:line 77
   at Mongo2Go.Helper.MongoBinaryLocator.get_Directory() in /_/src/Mongo2Go/Helper/MongoBinaryLocator.cs:line 59
   at Mongo2Go.MongoDbRunner.MakeMongoBinarysExecutable() in /_/src/Mongo2Go/MongoDbRunner.cs:line 212
   at Mongo2Go.MongoDbRunner..ctor(IPortPool portPool, IFileSystem fileSystem, IMongoDbProcessStarter processStarter, IMongoBinaryLocator mongoBin, String dataDirectory, Boolean singleNodeReplSet, String additionalMongodArguments, UInt16 singleNodeReplSetWaitTimeout, ILogger logger) in /_/src/Mongo2Go/MongoDbRunner.cs:line 192
   at Mongo2Go.MongoDbRunner.Start(String dataDirectory, String binariesSearchPatternOverride, String binariesSearchDirectory, Boolean singleNodeReplSet, String additionalMongodArguments, UInt16 singleNodeReplSetWaitTimeout, ILogger logger) in /_/src/Mongo2Go/MongoDbRunner.cs:line 46
   at [user code]
--IOException
```

From what I understand, mongo2go tries to guess the home folder of my user, but picks up a folder of another user, hence the permission problem. Indeed, my user is `flemaitre`and its home is `/home/flemaitre`, but the folder being used is `/home/test`.
I have seen the issue on Ubuntu 22.04, and on NixOS 22.05 (with different paths).

Before anyone suggests it, no, it is not reasonable to change the permission of the folder to make mongo2go work.

I think it is related to #97, however the issue is not about permission, but about not using the right folder.

**Comment by asimmon** [comment]
Hi @lemaitre-aneo , I recently created another project based on Mongo2Go because [I had several issues with it](https://github.com/Mongo2Go/Mongo2Go/issues/142). I believe this could solve yours:

https://github.com/asimmon/ephemeral-mongo

**Comment by JohannesHoppe** [comment]
I am now releasing a new version v4, please test if the bug is gone now. If so, please get back to me so that we can close this issue.
