### ISSUE TITLE
Getting error in CI pipeline in the github action

### ISSUE THREAD

**Issue by mehdihadeli** [Mongo2Go/Mongo2Go#144]
Hi,
I use Mongo2Go in my integration tests in the `GitHub Action` with `ubuntu:latest` runner, but in the CI pipeline I get below error:

``` bash
[xUnit.net 00:00:21.99]     [Test Collection Cleanup Failure (Integration Test)] System.NullReferenceException
  Failed should save mongo customer read model in internal persistence message [1 ms]
  Error Message:
   System.UnauthorizedAccessException : Access to the path '/home/runneradmin' is denied.
---- System.IO.IOException : Permission denied
  Stack Trace:
     at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetDirectories(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at Mongo2Go.Helper.FolderSearch.FindFolder(String startPath, String searchPattern) in /_/src/Mongo2Go/Helper/FolderSearch.cs:line 35
   at Mongo2Go.Helper.FolderSearch.FindFolderUpwards(String startPath, String searchPattern) in /_/src/Mongo2Go/Helper/FolderSearch.cs:line 62
   at Mongo2Go.Helper.FolderSearch.FindFolderUpwards(String startPath, String searchPattern) in /_/src/Mongo2Go/Helper/FolderSearch.cs:line 63
   at Mongo2Go.Helper.FolderSearch.FindFolderUpwards(String startPath, String searchPattern) in /_/src/Mongo2Go/Helper/FolderSearch.cs:line 63
   at Mongo2Go.Helper.FolderSearch.FindFolderUpwards(String startPath, String searchPattern) in /_/src/Mongo2Go/Helper/FolderSearch.cs:line 63
   at Mongo2Go.Helper.FolderSearch.FindFolderUpwards(String startPath, String searchPattern) in /_/src/Mongo2Go/Helper/FolderSearch.cs:line 63
   at Mongo2Go.Helper.FolderSearch.FindFolderUpwards(String startPath, String searchPattern) in /_/src/Mongo2Go/Helper/FolderSearch.cs:line 63
   at Mongo2Go.Helper.FolderSearch.FindFolderUpwards(String startPath, String searchPattern) in /_/src/Mongo2Go/Helper/FolderSearch.cs:line 63
   at Mongo2Go.Helper.FolderSearch.FindFolderUpwards(String startPath, String searchPattern) in /_/src/Mongo2Go/Helper/FolderSearch.cs:line 63
   at Mongo2Go.Helper.FolderSearch.FindFolderUpwards(String startPath, String searchPattern) in /_/src/Mongo2Go/Helper/FolderSearch.cs:line 63
   at Mongo2Go.Helper.FolderSearch.FindFolderUpwards(String startPath, String searchPattern) in /_/src/Mongo2Go/Helper/FolderSearch.cs:line 63
   at Mongo2Go.Helper.FolderSearch.FindFolderUpwards(String startPath, String searchPattern) in /_/src/Mongo2Go/Helper/FolderSearch.cs:line 63
   at Mongo2Go.Helper.FolderSearch.FindFolderUpwards(String startPath, String searchPattern) in /_/src/Mongo2Go/Helper/FolderSearch.cs:line 63
   at Mongo2Go.Helper.MongoBinaryLocator.FindBinariesDirectory(IList`1 searchDirectories) in /_/src/Mongo2Go/Helper/MongoBinaryLocator.cs:line 84
   at Mongo2Go.Helper.MongoBinaryLocator.ResolveBinariesDirectory() in /_/src/Mongo2Go/Helper/MongoBinaryLocator.cs:line 77
   at Mongo2Go.Helper.MongoBinaryLocator.get_Directory() in /_/src/Mongo2Go/Helper/MongoBinaryLocator.cs:line 59
   at Mongo2Go.MongoDbRunner.MakeMongoBinarysExecutable() in /_/src/Mongo2Go/MongoDbRunner.cs:line 212
   at Mongo2Go.MongoDbRunner..ctor(IPortPool portPool, IFileSystem fileSystem, IMongoDbProcessStarter processStarter, IMongoBinaryLocator mongoBin, String dataDirectory, Boolean singleNodeReplSet, String additionalMongodArguments, UInt16 singleNodeReplSetWaitTimeout, ILogger logger) in /_/src/Mongo2Go/MongoDbRunner.cs:line 192
   at Mongo2Go.MongoDbRunner.Start(String dataDirectory, String binariesSearchPatternOverride, String binariesSearchDirectory, Boolean singleNodeReplSet, String additionalMongodArguments, UInt16 singleNodeReplSetWaitTimeout, ILogger logger) in /_/src/Mongo2Go/MongoDbRunner.cs:line 46
   at Tests.Shared.Fixtures.Mongo2GoFixture.InitializeAsync() in /home/runner/work/ecommerce-microservices/ecommerce-microservices/tests/Shared/Tests.Shared/Fixtures/Mongo2GoFixture.cs:line 11
   at Tests.Shared.Fixtures.SharedFixture`1.InitializeAsync() in /home/runner/work/ecommerce-microservices/ecommerce-microservices/tests/Shared/Tests.Shared/Fixtures/SharedFixture.cs:line 137
----- Inner Stack Trace -----
```

**Comment by tn501** [comment]
:( ran into same problem

**Comment by mehdihadeli** [comment]
Should we use something like this for getting permission?
https://github.com/actions/checkout/issues/211#issuecomment-611986243
``` bash
sudo chown -R $USER:$USER /home/github/actions-runner/_work/{REPOSITORY_NAME_HERE}
```

**Comment by tllstrtzl** [comment]
based on @mehdihadeli proposed solution, i was able to get the tests working using the following step:
`    - name: test
        run: |
            sudo chown -R $USER:$USER /home/runneradmin
            dotnet test -c Release --no-build
`

**Comment by asimmon** [comment]
Please consider using https://github.com/asimmon/ephemeral-mongo instead as mentionned in Mongo2Go's README.

**Comment by JohannesHoppe** [comment]
@tonidy Could you provide a sample github action, that we integrate into our build? Looks like you found a solution, but your work relied on another action (mongodb-github-action) ?? But I still see some Mongo2Go references in your code?? =)

**Comment by tonidy** [comment]
@JohannesHoppe , to be honest, I had never run GitHub Actions in my repository until you mentioned me 😅. Surprisingly, my tests are passing! I also can’t quite recall why I opted for `mongodb-github-action` and testing with `Mongo2Go`.

Let me take a closer look.

Here are my green test results:

<img width="1041" alt="image" src="https://github.com/user-attachments/assets/5db9474e-7728-45d2-9876-1cbba8bbc3e0">

**Comment by JohannesHoppe** [comment]
Ok, that's funny. I'm glad to see that Mongo2Go + Github Actions works for you too. I think that's enough information to close this issue without bad feelings! 😇

**Comment by tonidy** [comment]
@JohannesHoppe I remembered now, so here are the details:

- I've two fixtures in my test setup: `DBFixture` which uses `mongodb-github-action` and `Mongo2GoFixture`- from the name you should know, right? 😉 
<img width="271" alt="image" src="https://github.com/user-attachments/assets/2f2ecb11-eb52-49d8-a508-cd121d36ace4">

- I believe this error occurs only when using xUnit as the test runner, since Mongo2Go relies on `Machine.Specifications`, so no error happened
- Here's the fix:

```yml
 - name: Test
      run: |
        sudo chown -R $USER:$USER /home/runneradmin
        cd test
        dotnet test --no-build --verbosity normal
```

I hope this's helpful to others

**Comment by JohannesHoppe** [comment]
Ahh! Yes, I have seen this `sudo chown -R $USER:$USER /home/runneradmin` multiple times now!
Thanks for this helpful explanation 🙂👍
