### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by gosquid005** [Mongo2Go/Mongo2Go#147]
Hi,
I'm facing a problem running my integration tests, with more than 200 unit tests, an exception is thrown if I execute them all at once, as demonstrated below. However, I was able to resolve this issue by breaking down the test cases and executing them in batches of around 50 at a time, which was successful.

- Mongo2Go: 3.1.3
- Os: macOs 13.2.1

<img width="298" alt="image" src="https://user-images.githubusercontent.com/102209498/225800470-8313c76b-d71f-4b38-9a90-f1bf2403c0e3.png">

```
 Error Message:
   Volo.Abp.AbpInitializationException : An error occurred during the initialize Volo.Abp.Modularity.OnApplicationInitializationModuleLifecycleContributor phase of the module GoSquid.GoSquidTestBaseModule, GoSquid.TestBase, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: Command create failed: 24: Too many open files.. See the inner exception for details.
---- MongoDB.Driver.MongoCommandException : Command create failed: 24: Too many open files.
  Stack Trace:
     at Volo.Abp.Modularity.ModuleManager.InitializeModules(ApplicationInitializationContext context)
   at Volo.Abp.AbpApplicationBase.InitializeModules()
   at Volo.Abp.Testing.AbpIntegratedTest`1..ctor()
   at GoSquid.GoSquidTestBase`1..ctor()
   at GoSquid.GoSquidApplicationTestBase..ctor()
   at GoSquid.Gameplays.GameplaysAppServiceTests..ctor() in /Users/thaingo/Sources/GoSquid/gosquid-suite/aspnet-core/test/GoSquid.Application.Tests/Gameplays/GameplayApplicationTests.cs:line 16
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
----- Inner Stack Trace -----
   at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.ProcessResponse(ConnectionId connectionId, CommandMessage responseMessage)
   at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.WireProtocol.CommandWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.ServerChannel.ExecuteProtocol[TResult](IWireProtocol`1 protocol, ICoreSession session, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.ServerChannel.Command[TResult](ICoreSession session, ReadPreference readPreference, DatabaseNamespace databaseNamespace, BsonDocument command, IEnumerable`1 commandPayloads, IElementNameValidator commandValidator, BsonDocument additionalOptions, Action`1 postWriteAction, CommandResponseHandling responseHandling, IBsonSerializer`1 resultSerializer, MessageEncoderSettings messageEncoderSettings, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.CommandOperationBase`1.ExecuteProtocol(IChannelHandle channel, ICoreSessionHandle session, ReadPreference readPreference, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.CommandOperationBase`1.ExecuteProtocol(IChannelSource channelSource, ICoreSessionHandle session, ReadPreference readPreference, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.WriteCommandOperation`1.Execute(IWriteBinding binding, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.CreateCollectionOperation.Execute(IWriteBinding binding, CancellationToken cancellationToken)
   at MongoDB.Driver.OperationExecutor.ExecuteWriteOperation[TResult](IWriteBinding binding, IWriteOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoDatabaseImpl.ExecuteWriteOperation[T](IClientSessionHandle session, IWriteOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoDatabaseImpl.CreateCollection(IClientSessionHandle session, String name, CreateCollectionOptions options, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoDatabaseImpl.UsingImplicitSession(Action`1 func, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoDatabaseImpl.CreateCollection(String name, CreateCollectionOptions options, CancellationToken cancellationToken)
   at Volo.Abp.MongoDB.MongoModelBuilder.CreateCollectionIfNotExists(AbpMongoDbContext dbContext, String collectionName)
   at Volo.Abp.MongoDB.MongoModelBuilder.Build(AbpMongoDbContext dbContext)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Volo.Abp.MongoDB.AbpMongoDbContext.GetEntityModel[TEntity]()
   at Volo.Abp.MongoDB.AbpMongoDbContext.GetCollectionName[T]()
   at Volo.Abp.MongoDB.AbpMongoDbContext.Collection[T]()
   at Volo.Abp.Domain.Repositories.MongoDB.MongoDbRepository`2.GetMongoQueryableAsync[TOtherEntity](CancellationToken cancellationToken, AggregateOptions aggregateOptions)
   at Volo.Abp.SettingManagement.MongoDB.MongoSettingRepository.GetListAsync(String providerName, String providerKey, CancellationToken cancellationToken)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Volo.Abp.SettingManagement.SettingManagementStore.SetCacheItemsAsync(String providerName, String providerKey, String currentName, SettingCacheItem currentCacheItem)
   at Volo.Abp.SettingManagement.SettingManagementStore.GetCacheItemAsync(String name, String providerName, String providerKey)
   at Volo.Abp.SettingManagement.SettingManagementStore.GetOrNullAsync(String name, String providerName, String providerKey)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Volo.Abp.Settings.UserSettingValueProvider.GetOrNullAsync(SettingDefinition setting)
   at Volo.Abp.Settings.SettingProvider.GetOrNullValueFromProvidersAsync(IEnumerable`1 providers, SettingDefinition setting)
   at Volo.Abp.Settings.SettingProvider.GetOrNullAsync(String name)
   at Volo.Abp.Settings.SettingProviderExtensions.GetAsync[T](ISettingProvider settingProvider, String name, T defaultValue)
   at Volo.Abp.Identity.AbpIdentityOptionsManager.OverrideOptionsAsync(String name, IdentityOptions options)
   at Volo.Abp.Identity.IdentityDataSeeder.SeedAsync(String adminEmail, String adminPassword, Nullable`1 tenantId)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Volo.Abp.Data.DataSeeder.SeedAsync(DataSeedContext context)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous(IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at GoSquid.GoSquidTestBaseModule.<>c__DisplayClass2_0.<<SeedTestData>b__0>d.MoveNext() in /Users/thaingo/Sources/GoSquid/gosquid-suite/aspnet-core/test/GoSquid.TestBase/GoSquidTestBaseModule.cs:line 41
--- End of stack trace from previous location ---
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException(Task task)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException(Task task)
   at Nito.AsyncEx.AsyncContext.Run(Func`1 action)
   at GoSquid.GoSquidTestBaseModule.SeedTestData(ApplicationInitializationContext context) in /Users/thaingo/Sources/GoSquid/gosquid-suite/aspnet-core/test/GoSquid.TestBase/GoSquidTestBaseModule.cs:line 37
   at GoSquid.GoSquidTestBaseModule.OnApplicationInitialization(ApplicationInitializationContext context) in /Users/thaingo/Sources/GoSquid/gosquid-suite/aspnet-core/test/GoSquid.TestBase/GoSquidTestBaseModule.cs:line 32
   at Volo.Abp.Modularity.ModuleManager.InitializeModules(ApplicationInitializationContext context)

```

**Comment by teneko** [comment]
This is actually a problem. When running test cases, I also face the problem Windows, that processes are not correctly getting killed resulting in so many staling mongo db processes. I am not entirely sure, how Xunit behaves, but is  AppDomain.CurrentDomain.ProcessExit an option? If no programmatically solution is is in view in context of Xunit runner, is a msbuild test post hook the last resort? We would have to reproduce and construct a proper test case for this. What's your thought on this @JohannesHoppe?

**Comment by JohannesHoppe** [comment]
@teneko , you deleted your last message, but I still want to answer it.

First, thanks for bringing this up!
I don’t have a Windows machine to test this myself, but I’m open to any PR that improves process cleanup in Mongo2Go. 😇

**Comment by JohannesHoppe** [comment]
Fixed in **Mongo2Go 5.0.0**. Several process handles and one `MongoClient` weren't being disposed, leaking file descriptors on every runner start and every import/export — exactly why running a large suite (your ~200 tests) hit the OS open-file limit while smaller batches were fine. 5.0.0 now disposes them deterministically: the `chmod` process, the `mongoimport`/`mongoexport` processes (and their redirected pipes), and the replica-set-init `MongoClient`. Thanks for the clear repro.
