### ISSUE TITLE
Upgrading to version 3 driver

### ISSUE THREAD

**Issue by MahmoudH96** [Mongo2Go/Mongo2Go#152]
As MongoDB team released a [new version of their driver v3.0.0](https://github.com/mongodb/mongo-csharp-driver/releases/tag/v3.0.0) are there any plans to upgrade the dependency inside Mongo2Go as having MongoDB driver version 3 alongside Mongo2Go is causing the following exception:

`System.TypeLoadException : Could not load type 'MongoDB.Driver.MongoClientBase' from assembly 'MongoDB.Driver, Version=3.0.0.0, Culture=neutral, PublicKeyToken=94992a530f44e321'.
  Stack Trace:
     at Mongo2Go.Helper.MongoDbProcessStarter.Start(String binariesDirectory, String dataDirectory, Int32 port, Boolean doNotKill, Boolean singleNodeReplSet, String additionalMongodArguments, UInt16 singleNodeReplSetWaitTimeout, ILogger logger)
   at Mongo2Go.Helper.MongoDbProcessStarter.Start(String binariesDirectory, String dataDirectory, Int32 port, Boolean singleNodeReplSet, String additionalMongodArguments, UInt16 singleNodeReplSetWaitTimeout, ILogger logger) in /_/src/Mongo2Go/Helper/MongoDbProcessStarter.cs:line 25
   at Mongo2Go.MongoDbRunner..ctor(IPortPool portPool, IFileSystem fileSystem, IMongoDbProcessStarter processStarter, IMongoBinaryLocator mongoBin, String dataDirectory, Boolean singleNodeReplSet, String additionalMongodArguments, UInt16 singleNodeReplSetWaitTimeout, ILogger logger) in /_/src/Mongo2Go/MongoDbRunner.cs:line 202
   at Mongo2Go.MongoDbRunner.Start(String dataDirectory, String binariesSearchPatternOverride, String binariesSearchDirectory, Boolean singleNodeReplSet, String additionalMongodArguments, UInt16 singleNodeReplSetWaitTimeout, ILogger logger) in /_/src/Mongo2Go/MongoDbRunner.cs:line 46
   at Tabley.Test.DataSource.GroupRepositoryTest..ctor() in <code>
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)`

**Comment by JohannesHoppe** [comment]
I'm not actively developing Mongo2Go anymore. But you are welcome to upgrade everything to v3 and to sent me a PR. But be warned, adding pre-compiled binaries to a nuget package wasn't the best idea in retrospective. Things just break in different environments for no reasons, eg. Azure seems to be a big issue. In the end I don't care any longer, MongoDB and .NET was cool 10 years ago, but it's not my choice any longer.

**Comment by DrewM-Hax0r** [comment]
Hi, I forked this and upgraded the version of the driver to version 3. I created a pull request for it.

**Comment by peterkiss1** [comment]
@JohannesHoppe any chance to get the PR for this merged & release a new package?

**Comment by cakj** [comment]
Seems to be merged now, hoping for a release pretty soon :-)

**Comment by JohannesHoppe** [comment]
I'm cooking a new release right now. I also merged all open PRs. Please test it when it's on Nuget! 😊

**Comment by JohannesHoppe** [comment]
fixed via #153
