### ISSUE TITLE
mongo2go linux netcore 1.1

### ISSUE THREAD

**Issue by bastiflew** [Mongo2Go/Mongo2Go#37]
Hello,

I have an issue with mongo2go in a linux environment, using the 2.0.0-aplha1 version.
the method MakeFileExecutable() throws an exception :

```
Invalid File or Directory attributes value
           at System.IO.FileSystemInfo.System.IO.IFileSystemObject.set_Attributes(FileAttributes value)
           at System.IO.UnixFileSystem.SetAttributes(String fullPath, FileAttributes attributes)
           at System.IO.File.SetAttributes(String path, FileAttributes fileAttributes)
        /data/projects/Mongo2Go/src/Mongo2Go/Helper/FileSystem.cs(35,0): at Mongo2Go.Helper.FileSystem.MakeFileExecutable(String path)
        /data/projects/Mongo2Go/src/Mongo2Go/MongoDbRunner.cs(137,0): at Mongo2Go.MongoDbRunner.MakeMongoBinarysExecutable()
        /data/projects/Mongo2Go/src/Mongo2Go/MongoDbRunner.cs(120,0): at Mongo2Go.MongoDbRunner..ctor(IPortPool portPool, IFileSystem fileSystem, IMongoDbProcessStarter processStarter, IMongoBinaryLocator mongoBin, String dataDirectory)
        /data/projects/Mongo2Go/src/Mongo2Go/MongoDbRunner.cs(37,0): at Mongo2Go.MongoDbRunner.Start(String dataDirectory, String searchPatternOverride)
```
if I comment this line, everything works as excepted.

Thanks

**Comment by sunsided** [comment]
I tried that as well, but then it couldn't start the process unless I explicitly made the binaries executable in the `.nuget` package cache.

**Comment by Johlandabee** [comment]
As far as I know, setting the executable bit through the API is currently not supported by Core 1.x. Thus this functionality is broken in the current Mongo2Go release.

A relatively straight forward fix would be something like:
````csharp
private static void SetExecutableBit(string file)
{
    // Workaround until dotnet core 2.0
    var p = Process.Start("chmod", $"+x {file}");
    p.WaitForExit();

    if (p.ExitCode != 0)
        throw new CouldNotSetExecutableBit($"Could not set executable bit for {file}");
}
````

I took this snippet from my [WIP rewrite of Mongo2Go](https://github.com/Johlandabee/Amongst).

**Comment by JohannesHoppe** [comment]
see also: https://github.com/Mongo2Go/Mongo2Go/commit/26fc47a578da1fe104fb0b83f5cf1b096ece4e3e
