### ISSUE TITLE
Custom Bson Serialization

### ISSUE THREAD

**Issue by reeloadead** [Mongo2Go/Mongo2Go#75]
I use custom Bson serialization in my app:
```
var pack = new ConventionPack {new CamelCaseElementNameConvention()};
ConventionRegistry.Register("camelCaseConvention", pack, t => true);
BsonClassMap.RegisterClassMap<MyDocument>(m =>
{
   m.AutoMap();
   m.SetIdMember(m.GetMemberMap(e => e.MyId));
});
```

If I register my naming convention (code from above) in integration tests with  `Mongo2Go`, I got error:
```
System.ArgumentException
An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at MongoDB.Bson.Serialization.BsonClassMap.RegisterClassMap(BsonClassMap classMap)
```

If I do not register my naming convention, I got error:
```
System.FormatException
Element '_id' does not match any field or property of class MongoDB.Bson.Serialization.BsonClassMapSerializer`1.DeserializeClass(BsonDeserializationContext context)
   at MongoDB.Bson.Serialization.BsonClassMapSerializer`1.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
```

Is it possible to teach `Mongo2Go` to work with custom serializations? What do you think from architecture side?

**Comment by reeloadead** [comment]
It was my fault, sorry. All it need is to to Register your own classes in proper way.
