### ISSUE TITLE
Upgrade mongodb to 4.2.1

### ISSUE THREAD

**Issue by pkrReviso** [Mongo2Go/Mongo2Go#85]
Currently, I am getting following error while using mongo2go:

`Transaction numbers are only allowed on a replica set member or mongos`
```
Usage:
 var mongoCollection = GetDeliveryNoteCollection(connection.MongoConnection);
 var notesFromSession = mongoCollection.Aggregate(connection.MongoSession)
						.Match(note => note.Id == Id)
						.ToList();

Exception:
MongoDB.Driver.MongoCommandException
  HResult=0x80131500
  Message=This MongoDB deployment does not support retryable writes. Please add retryWrites=false to your connection string.
  Source=MongoDB.Driver.Core
  StackTrace:
   at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.ProcessResponse(ConnectionId connectionId, CommandMessage responseMessage)
   at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.WireProtocol.CommandWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.ServerChannel.ExecuteProtocol[TResult](IWireProtocol`1 protocol, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.ServerChannel.Command[TResult](ICoreSession session, ReadPreference readPreference, DatabaseNamespace databaseNamespace, BsonDocument command, IEnumerable`1 commandPayloads, IElementNameValidator commandValidator, BsonDocument additionalOptions, Action`1 postWriteAction, CommandResponseHandling responseHandling, IBsonSerializer`1 resultSerializer, MessageEncoderSettings messageEncoderSettings, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.CommandOperationBase`1.ExecuteProtocol(IChannelHandle channel, ICoreSessionHandle session, ReadPreference readPreference, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.ReadCommandOperation`1.ExecuteAttempt(RetryableReadContext context, Int32 attempt, Nullable`1 transactionNumber, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.RetryableReadOperationExecutor.Execute[TResult](IRetryableReadOperation`1 operation, RetryableReadContext context, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.ReadCommandOperation`1.Execute(RetryableReadContext context, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.AggregateOperation`1.Execute(RetryableReadContext context, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.AggregateOperation`1.Execute(IReadBinding binding, CancellationToken cancellationToken)
   at MongoDB.Driver.OperationExecutor.ExecuteReadOperation[TResult](IReadBinding binding, IReadOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.ExecuteReadOperation[TResult](IClientSessionHandle session, IReadOperation`1 operation, ReadPreference readPreference, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.ExecuteReadOperation[TResult](IClientSessionHandle session, IReadOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.Aggregate[TResult](IClientSessionHandle session, PipelineDefinition`2 pipeline, AggregateOptions options, CancellationToken cancellationToken)
   at MongoDB.Driver.CollectionAggregateFluent`2.ToCursor(CancellationToken cancellationToken)
   at MongoDB.Driver.IAsyncCursorSourceExtensions.ToList[TDocument](IAsyncCursorSource`1 source, CancellationToken cancellationToken)
   at Reviso.DeliveryNote.Dal.Repositories.DeliveryNoteRepository.<>c__DisplayClass7_0.<GetAll>b__0() in C:\src\delivery-note-app\server\Reviso.DeliveryNote.Dal\Repositories\DeliveryNoteRepository.cs:line 56
   at Polly.Policy.<>c__DisplayClass114_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)

Inner Exception 1:
MongoCommandException: Command aggregate failed: Transaction numbers are only allowed on a replica set member or mongos.
```

**Comment by DR9885** [comment]
I had a similar issue with Mongo2Go, and used this -> MongoDbRunner.Start(singleNodeReplSet: true);

**Comment by staxDB** [comment]
I would be very happy if the MongoDB version would be updated. There are some new aggregation pipeline stages that I would like to use: https://docs.mongodb.com/manual/reference/operator/aggregation/replaceWith/

**Comment by JohannesHoppe** [comment]
https://github.com/Mongo2Go/Mongo2Go/pull/77#issuecomment-528436726  🙂👍
