### ISSUE TITLE
Binaries seem to include the full path of the development machine

### ISSUE THREAD

**Issue by AndreasTruetschel** [Mongo2Go/Mongo2Go#96]
The binaries on nuget include the full path where the repository on the build machine was located when creating the nuget package.  For example a stack trace of an exception thrown in the `MongoDbRunner` looks like this:
```
AI4E.Storage.MongoDB.Test.MongoDatabaseScopeTest.GetAsyncReflectsNonCommitedChangesTest [FAIL]
at MongoDB.Driver.Core.Operations.RetryableReadOperationExecutor.Execute[TResult](IRetryableReadOperation`1 operation, RetryableReadContext context, CancellationToken cancellationToken)
at MongoDB.Driver.Core.Operations.ReadCommandOperation`1.Execute(RetryableReadContext context, CancellationToken cancellationToken)
at MongoDB.Driver.Core.Operations.ReadCommandOperation`1.Execute(IReadBinding binding, CancellationToken cancellationToken)
at MongoDB.Driver.OperationExecutor.ExecuteReadOperation[TResult](IReadBinding binding, IReadOperation`1 operation, CancellationToken cancellationToken)
at MongoDB.Driver.MongoDatabaseImpl.ExecuteReadOperation[T](IClientSessionHandle session, IReadOperation`1 operation, ReadPreference readPreference, CancellationToken cancellationToken)
at MongoDB.Driver.MongoDatabaseImpl.RunCommand[TResult](IClientSessionHandle session, Command`1 command, ReadPreference readPreference, CancellationToken cancellationToken)
at MongoDB.Driver.MongoDatabaseImpl.UsingImplicitSession[TResult](Func`2 func, CancellationToken cancellationToken)
at MongoDB.Driver.MongoDatabaseImpl.RunCommand[TResult](Command`1 command, ReadPreference readPreference, CancellationToken cancellationToken)
W:\johanneshoppe\Mongo2Go\src\Mongo2Go\Helper\MongoDbProcessStarter.cs(64,0): at Mongo2Go.Helper.MongoDbProcessStarter.Start(String binariesDirectory, String dataDirectory, Int32 port, Boolean doNotKill, Boolean singleNodeReplSet, String additionalMongodArguments, UInt16 singleNodeReplSetWaitTimeout)
W:\johanneshoppe\Mongo2Go\src\Mongo2Go\Helper\MongoDbProcessStarter.cs(22,0): at Mongo2Go.Helper.MongoDbProcessStarter.Start(String binariesDirectory, String dataDirectory, Int32 port, Boolean singleNodeReplSet, String additionalMongodArguments, UInt16 singleNodeReplSetWaitTimeout)
W:\johanneshoppe\Mongo2Go\src\Mongo2Go\MongoDbRunner.cs(198,0): at Mongo2Go.MongoDbRunner..ctor(IPortPool portPool, IFileSystem fileSystem, IMongoDbProcessStarter processStarter, IMongoBinaryLocator mongoBin, String dataDirectory, Boolean singleNodeReplSet, String additionalMongodArguments, UInt16 singleNodeReplSetWaitTimeout)
W:\johanneshoppe\Mongo2Go\src\Mongo2Go\MongoDbRunner.cs(43,0): at Mongo2Go.MongoDbRunner.Start(String dataDirectory, String binariesSearchPatternOverride, String binariesSearchDirectory, Boolean singleNodeReplSet, String additionalMongodArguments, UInt16 singleNodeReplSetWaitTimeout)
/Users/runner/work/AI4E/AI4E/src/Storage/test/AI4E.Storage.MongoDB.Test/MongoDatabaseScopeTest.cs(18,0): at AI4E.Storage.MongoDB.Test.MongoDatabaseScopeTest.CreateMongoDbRunner()
/Users/runner/work/AI4E/AI4E/src/Storage/test/AI4E.Storage.MongoDB.Test/MongoDatabaseScopeTest.cs(14,0): at AI4E.Storage.MongoDB.Test.MongoDatabaseScopeTest..cctor()
```

**Comment by JohannesHoppe** [comment]
I'm aware of this. But i don't think it does any harm at all. If somebody knows a way how to hide the folder, I'm also not against a PR! :-)
