### ISSUE TITLE
System.UnauthorizedAccessException: Access to the path '/home/lost+found' is denied.

### ISSUE THREAD

**Issue by abezulski** [Mongo2Go/Mongo2Go#97]
I'm having issue with my application on freshly installed Linux Mint 19 (and 20 as well). Same code works fine on Mac OS Mojave and Windows 10.

An exception is thrown while starting the client:
```
var mongoRunner = MongoDbRunner.StartForDebugging();
mongoRunner.Import("db", "c1", @"./App_Data/data.json", true);
```
Supplying arguments like binariesSearchDirectory: "./App_Data", dataDirectory: "./App_Data" or swapping .StartForDebugging() to .Start() still throws the exception below:

```
[09:32:26 FTL] System.UnauthorizedAccessException: Access to the path '/home/lost+found' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Mongo2Go.Helper.FolderSearch.FindFolder(String startPath, String searchPattern)
   at Mongo2Go.Helper.FolderSearch.FindFolderUpwards(String startPath, String searchPattern)
   at Mongo2Go.Helper.FolderSearch.FindFolderUpwards(String startPath, String searchPattern)
   at Mongo2Go.Helper.FolderSearch.FindFolderUpwards(String startPath, String searchPattern)
   at Mongo2Go.Helper.FolderSearch.FindFolderUpwards(String startPath, String searchPattern)
   at Mongo2Go.Helper.FolderSearch.FindFolderUpwards(String startPath, String searchPattern)
   at Mongo2Go.Helper.FolderSearch.FindFolderUpwards(String startPath, String searchPattern)
   at Mongo2Go.Helper.FolderSearch.FindFolderUpwards(String startPath, String searchPattern)
   at Mongo2Go.Helper.MongoBinaryLocator.FindBinariesDirectory(IList`1 searchDirectories)
   at Mongo2Go.Helper.MongoBinaryLocator.ResolveBinariesDirectory()
   at Mongo2Go.Helper.MongoBinaryLocator.get_Directory()
   at Mongo2Go.MongoDbRunner.MakeMongoBinarysExecutable()
   at Mongo2Go.MongoDbRunner..ctor(IProcessWatcher processWatcher, IPortWatcher portWatcher, IFileSystem fileSystem, IMongoDbProcessStarter processStarter, IMongoBinaryLocator mongoBin, Int32 port, String dataDirectory, Boolean singleNodeReplSet, String additionalMongodArguments, UInt16 singleNodeReplSetWaitTimeout)
   at Mongo2Go.MongoDbRunner.StartForDebugging(String dataDirectory, String binariesSearchPatternOverride, String binariesSearchDirectory, Boolean singleNodeReplSet, Int32 port, String additionalMongodArguments, UInt16 singleNodeReplSetWaitTimeout)
   at API.StartupMongoLocal.AddMongoClient(IServiceCollection services, IWebHostEnvironment env, IConfiguration configuration) in /home/ab/Work/API/Startup.MongoClient.cs:line 20
   at API.Startup.ConfigureServices(IServiceCollection services) in /home/ab/Work/API/Startup.cs:line 84
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass15_0.<BuildStartupServicesFilterPipeline>g__RunPipeline|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
```
dotnet --info output:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.301
 Commit:    7feb845744

Runtime Environment:
 OS Name:     linuxmint
 OS Version:  20
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.301/

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  3.1.301 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by abezulski** [comment]
After doing some other installs on VMs I think it might might be related to .net core itself. Other machines where Mongo2Go is working have .net core 3.1.1 installed.

**Comment by juancarrey** [comment]
It happened to me too, this seems to be a permission thing. 
I runned it with sudo and it worked just fine, also on Azure Pipelines it works fine as well.

Try adding your user permissions to /home/lost+found
