### ISSUE TITLE
Azure DevOps throw "System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host" occasionally

### ISSUE THREAD

**Issue by iron9light** [Mongo2Go/Mongo2Go#98]
My unit test is very simple:
```csharp
        [Fact]
        public async Task SomeTest()
        {
            using (var runner = MongoDbRunner.Start())
            {
                var myService = GetMyService(runner.ConnectionString);
                ...
            }
        }
```

It works fine in my dev machine.
But may be failed with SocketException occasionally (~50% will be failed).
`System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host`

**Comment by iron9light** [comment]
Find a work around: Just wait 1 sec aftor disposed runner.
```csharp
        [Fact]
        public async Task SomeTest()
        {
            using (var runner = MongoDbRunner.Start())
            {
                var myService = GetMyService(runner.ConnectionString);
                ...
            }
        }

        await Task.Delay(TimeSpan.FromSeconds(1));
```

I think `MongoDbRunner.Dispose()` should do more check to make sure it has released all resources.

**Comment by JohannesHoppe** [comment]
Pull request are welcome here! 😄 👍

**Comment by iron9light** [comment]
Optimized the workaround. Wait for the port is available.
```csharp
        [Fact]
        public async Task SomeTest()
        {
            int? port = null;
            using (var runner = MongoDbRunner.Start())
            {
                port = int.Parse(mongoDbRunner.ConnectionString.Substring("mongodb://127.0.0.1:".Length).Split('/', 2).First(), CultureInfo.InvariantCulture);
                var myService = GetMyService(runner.ConnectionString);
                ...
            }

            if (port != null)
            {
                var portWatcher = PortWatcherFactory.CreatePortWatcher();
                while (!portWatcher.IsPortAvailable(port.Value))
                {
                    await Task.Yield();
                }
            }
        }
```

Will create a Pull Request for this issue.

**Comment by JohannesHoppe** [comment]
😢

**Comment by psmorandi** [comment]
I'm having the same problem (close at least) with the latest version (3.1.3). Works pretty well on local machine (I even tested with parallel execution). But, on Azure DevOps is failing with timeout:
```
System.TimeoutException : A timeout occurred after 30000ms selecting a server using CompositeServerSelector{ Selectors = MongoDB.Driver.MongoClient+AreSessionsSupportedServerSelector, LatencyLimitingServerSelector{ AllowedLatencyRange = 00:00:00.0150000 } }. Client view of cluster state is { ClusterId : "1", Type : "Unknown", State : "Disconnected", Servers : [{ ServerId: "{ ClusterId : 1, EndPoint : "127.0.0.1:36893" }", EndPoint: "127.0.0.1:36893", ReasonChanged: "Heartbeat", State: "Disconnected", ServerVersion: , TopologyVersion: , Type: "Unknown", HeartbeatException: "MongoDB.Driver.MongoConnectionException: An exception occurred while opening a connection to the server.
---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (111): Connection refused 127.0.0.1:36893
at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
at System.Net.Sockets.Socket.<>c.<ConnectAsync>b__274_0(IAsyncResult iar)
--- End of stack trace from previous location where exception was thrown ---
at MongoDB.Driver.Core.Connections.TcpStreamFactory.ConnectAsync(Socket socket, EndPoint endPoint, CancellationToken cancellationToken)
at MongoDB.Driver.Core.Connections.TcpStreamFactory.CreateStreamAsync(EndPoint endPoint, CancellationToken cancellationToken)
at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync(CancellationToken cancellationToken)
--- End of inner exception stack trace ---
at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync(CancellationToken cancellationToken)
at MongoDB.Driver.Core.Servers.ServerMonitor.InitializeConnectionAsync(CancellationToken cancellationToken)
at MongoDB.Driver.Core.Servers.ServerMonitor.HeartbeatAsync(CancellationToken cancellationToken)", LastHeartbeatTimestamp: "2021-05-20T17:51:55.9191838Z", LastUpdateTimestamp: "2021-05-20T17:51:55.9191841Z" }] }.
```

Any luck with this issue?

**Comment by bart-degreed** [comment]
Same for me. v3.1.3 succeeds on my laptop, but [fails on cibuild](https://ci.appveyor.com/project/json-api-dotnet/jsonapidotnetcore-mongodb/builds/39720243/job/kfms23pt3u0ymyy6). Reverted back to v2.2.16, which [succeeds](https://ci.appveyor.com/project/json-api-dotnet/jsonapidotnetcore-mongodb/builds/39731855/job/9yhnw4oe9fv0kd8p).

**Comment by JohannesHoppe** [comment]
I don't use Azure DevOps, so I hope somebody here can figure out a solution!? 🤷‍♂️

**Comment by bart-degreed** [comment]
I'm using AppVeyor, not Azure DevOps.

**Comment by psmorandi** [comment]
I guess it's not tied to a specific CI/CD, maybe it's possible to reproduce with github actions?

**Comment by JohannesHoppe** [comment]
Nope, it runs flawlessly on GitHub Actions:
https://github.com/Mongo2Go/Mongo2Go/actions/runs/800634192

**Comment by psmorandi** [comment]
Something that me, @iron9light and @bart-degreed have in common: we are using xUnit. Seems that Mongo2Go uses Machine.Specifications. Maybe it's related with the way xUnit runner works. I will try to come up with some sort of MVP to reproduce this as open source project, maybe comparing both Machine.Specifications and xUnit.

**Comment by hkarina21** [comment]
Hello, I am having a similar problem with the error A timeout occurred after 
30000ms selecting a server using CompositeServerSelector{ Selectors = MongoDB.Driver.MongoClient+AreSessionsSupportedServerSelector, 
LatencyLimitingServerSelector{ AllowedLatencyRange = 00:00:00.0150000 }, OperationsCountServerSelector }. 
Client view of cluster state is { ClusterId : "107", ConnectionMode : "Direct", Type : "ReplicaSet", State : "Disconnected", Servers : [] }.

when setting the MongoDbRunner.Start() with the replicaSet flag to true and with the latest version of Mongo2Go (3.1.3)

When downgraded the Mongo2Go nuget package to the 2.2.16 version and having the same replicaSet flag set to true the unit tests are passing but 
it takes up to 40 minutes to run aprox 369 tests which is not ideal
Both of these scenarios are happening on local machine and on Azure DevOps as well 

To mention : having the latest version of Mongo2Go(3.1.3) and with the replicaSet flag set to false it works fine 

Any solutions on this?

**Comment by MykolaKushnarenko** [comment]
@psmorandi, @JohannesHoppe hi! Have you made any progress lately? Unfortunately, I've encountered the same issue. Locally, all my tests pass successfully. However, on AzureDevOps I still have time-outs for some reason.

**Comment by matusqo** [comment]
Hi all,
today I figured out after trying to run tests from command line directly on a build machine where the mongod.exe crashed right after start and therefore you get the timeout as the process is no longer running. Version 3.1.3 is equipped with mongod.exe version that is not supported by OS of the build machine which is Windows Server 2012 R2.

![image](https://user-images.githubusercontent.com/50449453/216041553-2504a815-4e53-4bb3-828e-18be90fc0a86.png)
![image](https://user-images.githubusercontent.com/50449453/216041950-e357caa2-bd44-4c36-abbe-978471c94e74.png)

Version 2.2.16 contains mongod.exe that is compatible with my OS.

But now I get "forcibly closed" exceptions in Azure Pipelines...

**Comment by JohannesHoppe** [comment]
Ok, it looks like this issue is related to a specific version of the MongoDB binaries. Updating them to the latest version might fix this. So it's a duplicate of https://github.com/Mongo2Go/Mongo2Go/issues/132

I'm closing this one now. But feel free to open this issue again.
